# Generated by Django 5.2.9 on 2026-01-02 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Codice univoco per l'URL (es. famiglia-rossi)", unique=True)),
                ('name', models.CharField(help_text='Nome visualizzato (es. Famiglia Rossi)', max_length=200)),
                ('accommodation_offered', models.BooleanField(default=False)),
                ('transfer_offered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affinities', models.ManyToManyField(blank=True, to='core.invitation')),
                ('non_affinities', models.ManyToManyField(blank=True, related_name='incompatible_with', to='core.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_child', models.BooleanField(default=False)),
                ('is_attending', models.BooleanField(blank=True, null=True)),
                ('dietary_requirements', models.TextField(blank=True, null=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='core.invitation')),
            ],
        ),
    ]
