# Generated by Django 5.2.9 on 2026-01-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_globalconfig_remove_person_is_attending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='requires_accommodation',
        ),
        migrations.RemoveField(
            model_name='person',
            name='requires_transfer',
        ),
        migrations.AddField(
            model_name='invitation',
            name='accommodation_requested',
            field=models.BooleanField(default=False, verbose_name='Richiede Alloggio'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='transfer_requested',
            field=models.BooleanField(default=False, verbose_name='Richiede Transfer'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='accommodation_offered',
            field=models.BooleanField(default=False, verbose_name='Alloggio Offerto'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='transfer_offered',
            field=models.BooleanField(default=False, verbose_name='Transfer Offerto'),
        ),
    ]
