# Generated by Django 5.2.9 on 2026-01-03 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_person_requires_accommodation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Alloggio')),
                ('address', models.TextField(verbose_name='Indirizzo Completo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alloggio',
                'verbose_name_plural': 'Alloggi',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_invitations', to='core.accommodation', verbose_name='Alloggio Assegnato'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, verbose_name='Numero/Nome Stanza')),
                ('capacity_adults', models.PositiveIntegerField(default=2, verbose_name='Capienza Adulti')),
                ('capacity_children', models.PositiveIntegerField(default=0, verbose_name='Capienza Bambini')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.accommodation', verbose_name='Alloggio')),
            ],
            options={
                'verbose_name': 'Stanza',
                'verbose_name_plural': 'Stanze',
                'unique_together': {('accommodation', 'room_number')},
            },
        ),
    ]
