# Generated by Django 5.2.9 on 2026-01-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_accommodation_invitation_accommodation_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Persone'},
        ),
        migrations.AddField(
            model_name='person',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_guests', to='core.room', verbose_name='Stanza Assegnata'),
        ),
    ]
