# Generated by Django 5.2.9 on 2026-01-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_person_options_person_assigned_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='invitation_link_secret',
            field=models.CharField(default='my-secret-wedding-key-2026', help_text='Chiave segreta per generare token di verifica link inviti', max_length=64, verbose_name='Chiave Segreta Link'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='unauthorized_message',
            field=models.TextField(default='Spiacenti, questo invito non è valido o è scaduto. Contatta gli sposi per maggiori informazioni.', verbose_name='Messaggio Non Autorizzato'),
        ),
    ]
