# Generated by Django 5.1.4 on 2026-01-14 17:40

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_whatsapptemplate_whatsappmessagequeue_whatsappmessageevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurabletext',
            name='language',
            field=models.CharField(db_index=True, default='it', help_text='Codice lingua ISO (it, en, es...)', max_length=5, verbose_name='Lingua'),
        ),
        migrations.AlterUniqueTogether(
            name='configurabletext',
            unique_together={('key', 'language')},
        ),
        migrations.AlterModelOptions(
            name='configurabletext',
            options={'ordering': ['key', 'language'], 'verbose_name': 'Testo Configurabile', 'verbose_name_plural': 'Testi Configurabili'},
        ),
    ]
