# Generated by Django 5.2.9 on 2026-01-03 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_globalconfig_invitation_link_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestHeatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='ID univoco sessione frontend', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mouse_data', models.JSONField(default=list)),
                ('screen_width', models.IntegerField(default=0)),
                ('screen_height', models.IntegerField(default=0)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmaps', to='core.invitation')),
            ],
            options={
                'verbose_name': 'Heatmap Ospite',
                'verbose_name_plural': 'Heatmaps Ospiti',
            },
        ),
        migrations.CreateModel(
            name='GuestInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('visit', 'Visita Pagina'), ('click_cta', 'Click CTA'), ('rsvp_submit', 'Invio RSVP'), ('rsvp_reset', 'Reset RSVP')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, help_text='Mobile, Desktop, Tablet', max_length=50, null=True)),
                ('geo_country', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_city', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dati extra (es. button_id)')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.invitation')),
            ],
            options={
                'verbose_name': 'Interazione Ospite',
                'verbose_name_plural': 'Interazioni Ospiti',
                'ordering': ['-timestamp'],
            },
        ),
    ]
