# Generated by Django 5.2.9 on 2026-01-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_guestheatmap_guestinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('groom', 'Sposo'), ('bride', 'Sposa')], max_length=10)),
                ('recipient_number', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('processing', 'In Elaborazione'), ('sent', 'Inviato'), ('failed', 'Fallito'), ('skipped', 'Saltato (Rate Limit)')], default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(auto_now_add=True, help_text="Quando provare l'invio")),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Coda Messaggi WhatsApp',
                'verbose_name_plural': 'Coda Messaggi WhatsApp',
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSessionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('groom', 'Sposo'), ('bride', 'Sposa')], max_length=10, unique=True)),
                ('state', models.CharField(choices=[('disconnected', 'Disconnesso'), ('waiting_qr', 'In Attesa QR Code'), ('connected', 'Connesso'), ('error', 'Errore')], default='disconnected', max_length=20)),
                ('last_qr_code', models.TextField(blank=True, null=True)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Status Sessione WhatsApp',
                'verbose_name_plural': 'Status Sessioni WhatsApp',
            },
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='whatsapp_bride_firstname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Sposa'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='whatsapp_bride_lastname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cognome Sposa'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='whatsapp_bride_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero Sposa'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='whatsapp_groom_firstname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Sposo'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='whatsapp_groom_lastname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cognome Sposo'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='whatsapp_groom_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero Sposo (es. 39333...)'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='whatsapp_rate_limit',
            field=models.IntegerField(default=10, help_text='Massimo messaggi inviabili per ora per sessione (Safety Buffer)', verbose_name='Rate Limit (msg/ora)'),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='whatsapp_typing_simulation',
            field=models.BooleanField(default=True, verbose_name='Simula Digitazione Umana'),
        ),
    ]
