# Generated by Django 5.2.9 on 2026-01-06 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_whatsappmessagequeue_whatsappsessionstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('queued', 'Accodato'), ('waiting_rate_limit', 'In Attesa Rate Limit'), ('rate_limit_ok', 'Rate Limit Superato'), ('reading', 'Lettura Messaggi'), ('waiting_human', 'Attesa Umana'), ('typing', 'Digitazione'), ('sending', 'Invio'), ('sent', 'Inviato'), ('failed', 'Fallito'), ('skipped', 'Saltato')], max_length=30, verbose_name='Fase')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('duration_ms', models.IntegerField(blank=True, help_text='Durata della fase in millisecondi (se applicabile)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dati extra (es. rate_limit_remaining, typing_duration_ms, error_detail)')),
                ('queue_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.whatsappmessagequeue', verbose_name='Messaggio Coda')),
            ],
            options={
                'verbose_name': 'Evento Messaggio WhatsApp',
                'verbose_name_plural': 'Eventi Messaggi WhatsApp',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['queue_message', 'timestamp'], name='core_whatsa_queue_m_9385d2_idx'), models.Index(fields=['phase'], name='core_whatsa_phase_b54d00_idx')],
            },
        ),
    ]
