# Generated by Django 6.0.1 on 2026-01-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_whatsappmessageevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='origin',
            field=models.CharField(choices=[('groom', 'Lato Sposo'), ('bride', 'Lato Sposa')], default='groom', max_length=10, verbose_name='Appartenenza'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero Telefono (Referente)'),
        ),
    ]
