# Generated by Django 6.0.1 on 2026-01-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_invitation_origin_invitation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('created', 'Creato'), ('sent', 'Inviato'), ('read', 'Letto'), ('confirmed', 'Accettato'), ('declined', 'Declinato')], default='created', max_length=20, verbose_name='Stato Invito'),
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descrittivo del template', max_length=100)),
                ('condition', models.CharField(choices=[('status_change', 'Cambio di Stato'), ('manual', 'Manuale (Spot)')], default='status_change', max_length=20)),
                ('trigger_status', models.CharField(blank=True, choices=[('created', 'Creato'), ('sent', 'Inviato'), ('read', 'Letto'), ('confirmed', 'Accettato'), ('declined', 'Declinato')], help_text="Stato che attiva l'invio automatico", max_length=20, null=True)),
                ('content', models.TextField(help_text='Usa {name}, {link}, {code} come placeholder')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template WhatsApp',
                'verbose_name_plural': 'Template WhatsApp',
                'unique_together': {('trigger_status', 'condition')},
            },
        ),
    ]
