# Generated by Django 6.0.1 on 2026-01-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_invitation_status_whatsapptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='contact_verified',
            field=models.CharField(choices=[('not_valid', 'Numero non valido/assente'), ('not_exist', 'Non esiste su WhatsApp'), ('not_present', 'Non in rubrica'), ('ok', 'OK (Verificato)')], default='not_valid', max_length=20, verbose_name='Stato Verifica Contatto'),
        ),
    ]
