# Generated by Django 6.0.1 on 2026-01-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_invitation_contact_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='travel_car_with',
            field=models.BooleanField(blank=True, help_text='True se traghetto + auto al seguito', null=True, verbose_name='Auto al Seguito'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='travel_carpool_interest',
            field=models.BooleanField(blank=True, help_text='True se aereo + interesse carpool', null=True, verbose_name='Interesse Carpool'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='travel_schedule',
            field=models.TextField(blank=True, help_text='Orari partenza/arrivo (free-text)', null=True, verbose_name='Orari Viaggio'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='travel_transport_type',
            field=models.CharField(blank=True, help_text="Tipo trasporto: 'traghetto', 'aereo'", max_length=20, null=True, verbose_name='Tipo Trasporto'),
        ),
        migrations.AddField(
            model_name='person',
            name='not_coming',
            field=models.BooleanField(default=False, help_text='True se deselezionato nel wizard RSVP (escluso da conteggi e assignment)', verbose_name='Non Partecipa'),
        ),
        migrations.AlterField(
            model_name='guestinteraction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Dati extra (es. button_id, phone_number_old, phone_number_new)'),
        ),
    ]
