# Generated by Django 6.0.1 on 2026-01-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_invitation_travel_car_with_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='travel_car_with',
            field=models.CharField(choices=[('none', 'Non Disponibile'), ('noleggio', 'Auto a Noleggio'), ('proprio', 'Auto Propria')], default='none', help_text='True se auto disponibile', max_length=10, verbose_name='Auto disponibile'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='travel_carpool_interest',
            field=models.BooleanField(blank=True, help_text='True se interesse carpool', null=True, verbose_name='Interesse Carpool'),
        ),
    ]
