# Generated by Django 6.0.1 on 2026-01-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_invitation_travel_car_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsessionstatus',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappsessionstatus',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappsessionstatus',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
