# Generated by Django 6.0.1 on 2026-01-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_whatsappsessionstatus_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestinteraction',
            name='session_id',
            field=models.CharField(blank=True, default='unknown', help_text='ID univoco sessione frontend', max_length=100),
        ),
    ]
