# Generated by Django 4.2.7 on 2026-01-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_whatsappsessionstatus_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestinteraction',
            name='session_id',
            field=models.CharField(
                blank=True,
                default='unknown',
                help_text='ID univoco sessione frontend',
                max_length=100
            ),
        ),
    ]
