# Generated by Django 6.0.1 on 2026-01-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_guestinteraction_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestinteraction',
            name='event_type',
            field=models.CharField(choices=[('visit', 'Visita Pagina'), ('click_cta', 'Click CTA'), ('rsvp_submit', 'Invio RSVP'), ('rsvp_reset', 'Reset RSVP')], max_length=50),
        ),
    ]
