# Generated by Django 6.0.1 on 2026-01-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_guestinteraction_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('imported', 'Importato'), ('created', 'Creato'), ('sent', 'Inviato'), ('read', 'Letto'), ('confirmed', 'Accettato'), ('declined', 'Declinato')], default='created', max_length=20, verbose_name='Stato Invito'),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='trigger_status',
            field=models.CharField(blank=True, choices=[('imported', 'Importato'), ('created', 'Creato'), ('sent', 'Inviato'), ('read', 'Letto'), ('confirmed', 'Accettato'), ('declined', 'Declinato')], help_text="Stato che attiva l'invio automatico", max_length=20, null=True),
        ),
    ]
