# Generated by Django 6.0.1 on 2026-01-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_invitation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurableText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text="Chiave univoca per identificare il testo (es. 'envelope.front.content')", max_length=255, unique=True, verbose_name='Chiave')),
                ('content', models.TextField(help_text="Contenuto HTML con inline styles (es. <span style='font-family: serif;'>Testo</span>)", verbose_name='Contenuto')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadati per editor WYSIWYG (es. {"sections": [{"text": "...", "font": "serif"}]})', verbose_name='Metadati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
            ],
            options={
                'verbose_name': 'Testo Configurabile',
                'verbose_name_plural': 'Testi Configurabili',
                'ordering': ['key'],
            },
        ),
    ]
