# Generated by Django 6.0.1 on 2026-01-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_configurabletext_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome Etichetta')),
                ('color', models.CharField(default='#CCCCCC', max_length=7, verbose_name='Colore (HEX)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etichetta Invito',
                'verbose_name_plural': 'Etichette Invito',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='accommodation_pinned',
            field=models.BooleanField(default=False, help_text="Se attivo, l'algoritmo di auto-assegnazione non modificherà l'alloggio di questo invito.", verbose_name='Blocca Assegnazione Alloggio'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='invitations', to='core.invitationlabel', verbose_name='Etichette'),
        ),
    ]
