# Generated by Django 6.0.1 on 2026-01-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_invitationlabel_invitation_accommodation_pinned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Prezzo Camera'),
        ),
    ]
