# Generated by Django 6.0.1 on 2026-01-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='accommodation_pinned',
        ),
        migrations.AddField(
            model_name='person',
            name='accommodation_pinned',
            field=models.BooleanField(default=False, help_text="Se attivo, l'algoritmo di auto-assegnazione non modificherà l'alloggio di questo invito.", verbose_name='Blocca Assegnazione Alloggio'),
        ),
    ]
