# Generated by Django 6.0.1 on 2026-01-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_invitation_accommodation_pinned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='recipient',
            field=models.CharField(choices=[('spouse', 'Coniuge'), ('guest', 'Invitato')], default='guest', max_length=20),
        ),
    ]
