# Generated by Django 6.0.1 on 2026-01-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_whatsapptemplate_recipient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='whatsapptemplate',
            unique_together={('trigger_status', 'condition', 'recipient')},
        ),
    ]
