# Generated by Django 6.0.1 on 2026-02-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_whatsapptemplate_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome Tipo Fornitore')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo Fornitore',
                'verbose_name_plural': 'Tipi Fornitore',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Fornitore')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Valuta')),
                ('contact', models.JSONField(blank=True, default=dict, null=True, verbose_name='Contatti')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='core.suppliertype', verbose_name='Tipo Fornitore')),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
                'ordering': ['name'],
            },
        ),
    ]
