# Generated by Django 6.0.6 on 2026-06-04 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0026_suppliertype_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome Piattaforma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Piattaforma Pagamento',
                'verbose_name_plural': 'Piattaforme Pagamento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID Entità')),
                ('label', models.CharField(help_text='Es: Acconto, Saldo, Rata 1, Caparra', max_length=100, verbose_name='Etichetta')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importo')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Valuta')),
                ('payment_date', models.DateField(verbose_name='Data Pagamento')),
                ('status', models.CharField(choices=[('planned', 'Pianificato'), ('paid', 'Pagato'), ('cancelled', 'Annullato')], default='planned', max_length=20, verbose_name='Stato')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo Entità')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymentplatform', verbose_name='Piattaforma')),
            ],
            options={
                'verbose_name': 'Evento Pagamento',
                'verbose_name_plural': 'Eventi Pagamento',
                'ordering': ['payment_date'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_paymen_content_0a28da_idx'), models.Index(fields=['status'], name='core_paymen_status_fbf5e2_idx'), models.Index(fields=['payment_date'], name='core_paymen_payment_d0882c_idx')],
            },
        ),
    ]
