# Generated by Django 6.0.6 on 2026-06-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_paymentplatform_paymentevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Costo Pasto',
                'verbose_name_plural': 'Costo Pasto',
            },
        ),
    ]
